// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbIGt7A2CqFYE6NDfNUB42twOULpSEI1U',
    appId: '1:304798199292:android:0d4790a09a8b8eae6f5679',
    messagingSenderId: '304798199292',
    projectId: 'fiap-54edf',
    databaseURL: 'https://fiap-54edf-default-rtdb.firebaseio.com',
    storageBucket: 'fiap-54edf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD13CmJmN3T8WuH7dKqYZmfD0a4Bqotxr0',
    appId: '1:304798199292:ios:5ba06ccea85fb7ed6f5679',
    messagingSenderId: '304798199292',
    projectId: 'fiap-54edf',
    databaseURL: 'https://fiap-54edf-default-rtdb.firebaseio.com',
    storageBucket: 'fiap-54edf.appspot.com',
    iosClientId: '304798199292-0f001fk4uhdnf916ttoi8fcsnuj8n3vh.apps.googleusercontent.com',
    iosBundleId: 'com.example.trabalho2',
  );
}
